Commit changing files
DarkLord5/Skyrim-Character pull request #2
Opened 2021-10-09 17:32 UTC by DarkLord5

2021-10-09 21:24 UTC, seventh-attempt requested changes

2021-10-09 21:24 UTC, seventh-attempt commented on Program.cs
> +            var propertyArr = new int[paramCount, 2];
чем задавать ручками `paramCount` можно использовать BaseDict.Count

2021-10-09 21:24 UTC, seventh-attempt commented on Program.cs
>              TextLocalization localizer = new(language);
передавай filepath в конструктор `TextLocalization`, тогда в конструкторе не придётся проверять язык и по второму кругу указывать путь к файлу

2021-10-09 21:24 UTC, seventh-attempt commented on Program.cs
> +            using StreamReader sr = new(filepath);
ты считываешь файл дважды: один раз в локализаторе, второй раз здесь. Лучше считывать его в локализаторе, задавать как атрибут, и получать к нему доступ как `localizer.baseDict`

2021-10-09 21:24 UTC, seventh-attempt commented on Program.cs
> +            Console.WriteLine(localizer.JustText(1));
я всё же не понимаю зачем использовать цифры в качестве ключей. глянь как тут сделано https://github.com/seventh-attempt/skyrim-character-randomizer/blob/dev/translations/en.json. Основная проблема в том, что по цифре не понятно что происходит. Т.е. мне, чтобы понять, что же ты собираешься выводить, нужно лезть в файл с переводами и смотреть что там под номером один

2021-10-09 21:24 UTC, seventh-attempt commented on Program.cs
> +            Console.WriteLine(localizer.JustText(1));
Сделай отдельный метод для вывода информации. Если источник вывода поменяется - нужно будет по всему коду менять твой Console.WriteLine на что-то другое

2021-10-09 21:24 UTC, seventh-attempt commented on Program.cs
> +            Console.WriteLine(localizer.JustText(1));
мне кажется лучше было бы в локализаторе использовать перегрузку, а не писать 3 метода с одной целью, но разными названиями

2021-10-09 21:24 UTC, seventh-attempt commented on Program.cs
>              Dictionary<int, string> RaceDict = LangDict["race"];
эти словари, если ты хочешь через них работать, лучше создать в локализаторе и дёргать их оттуда

2021-10-09 21:24 UTC, seventh-attempt commented on Program.cs
> +            for (int i = 1; i <= paramCount; i++)
зачем здесь нужен отдельный цикл? можно его содержимое вынести в цикл пониже

2021-10-09 21:24 UTC, seventh-attempt commented on public/translations/EngText.json
> +    "5": "Remember, Dovahkiin, now you are {1}. It so happened that your homeland is {2}. \nWork is not easy, because you are {3}. As I understand, you are {4}, well, it's your business. \nYour life
переводы обычно делаются модулями, а тут у тебя под 15 логически не связанных предложений в одном переводе. Опять же, посмотри вот [сюда](https://github.com/seventh-attempt/skyrim-character-randomizer/blob/16cd7376a846313a0ac0afde7946dfd8d5de1fe8/translations/en.json#L61)

2021-10-10 16:57 UTC, DarkLord5 commented on Program.cs
> +            Console.WriteLine(localizer.JustText(1));
В случае с аутпутом мне удобнее с цифрами, так как если я потеряю значение, найти его по численному ключу гораздо легче, чем вспоминать и  искать ключ-строку. 
По поводу перегрузки согласен, и отдельного вывода тож, как раз думал, что забыл какую-то фичу реализовать

2021-10-10 17:14 UTC, DarkLord5 commented on public/translations/EngText.json
> +    "5": "Remember, Dovahkiin, now you are {1}. It so happened that your homeland is {2}. \nWork is not easy, because you are {3}. As I understand, you are {4}, well, it's your business. \nYour life
Не гони, это словарь словарей, ключ от этих предложений связывает их.

2021-10-10 18:31 UTC, seventh-attempt requested changes

2021-10-10 18:31 UTC, seventh-attempt commented on InputOutputProvider.cs
> +            Console.WriteLine(text);
здесь было бы неплохо после вывода устанавливать обратно предыдущий цвет текста, если новый передан и он отличается от старого

2021-10-10 18:31 UTC, seventh-attempt commented on InputOutputProvider.cs
> +        public static void PrintToOneString(string text = "", ConsoleColor color = ConsoleColor.White)
не думаю, что провайдер вывода должен решать в одну строку пишется текст, или нет. Если хочешь скомбинировать несчколько выводов - лучше это сделать на уровне контроллера, а потом уже выводить через `PrintText`

2021-10-10 18:31 UTC, seventh-attempt commented on Program.cs
> +                InputOutputProvider.PrintText("Choose a language: 1)English(eng). 2)Russian(ru)");
чего это сообщение не добавил в json? вообще можно сразу создавать переводчик со стандартным языком (анлийским, к примеру),  и потом добавить опцию сменить язык, ну или двинуть в сторону выбора персонажа. Это просто предложение, делать или нет уже решай сам

2021-10-10 18:31 UTC, seventh-attempt commented on Program.cs
>              Dictionary<int, string> RaceDict = LangDict["race"];
бамп коменту. Я бы лучше создал коллекцию из ключей, через которую работал бы, а не разбирал бы словарь по частям. Можешь не менять, просто подумай над этим

2021-10-10 18:31 UTC, seventh-attempt commented on Program.cs
> +            var propertyArr = new int[BaseDict.Count, 2];
зачем каждый раз считать длину словаря? она же по логике приложения не должна меняться? так почему бы не сделать `int dictLenght = BaseDict.count`?

2021-10-10 18:31 UTC, seventh-attempt commented on Program.cs
> +                    InputOutputProvider.PrintText();
это новая строка перещд выводом?) Можно в `ReadText` передавать текст, который бы предлагал ввести параметр, мол Console.Write("Select a race: ")

2021-10-10 18:31 UTC, seventh-attempt commented on Program.cs
> +            InputOutputProvider.ReadText();
зачем это нужно?

2021-10-10 18:31 UTC, seventh-attempt commented on public/translations/EngText.json
> +    "5": "Remember, Dovahkiin, now you are {1}. It so happened that your homeland is {2}. \nWork is not easy, because you are {3}. As I understand, you are {4}, well, it's your business. \nYour life
у тебя ключ это "5". Каким образом он связывает твои выражения?

2021-10-10 18:31 UTC, seventh-attempt commented on TextLocalization.cs
> +        internal string TextOut(Dictionary<string, Dictionary<int, string>> LangDict, Dictionary<int, int> res, int code)
опять же, у тебя есть `LangDict` как атрибут класса, но ты его принимаешь как параметр. Зачем?

2021-10-10 18:31 UTC, seventh-attempt commented on public/translations/EngText.json
> +    "2": "Choose {param} yourself, put the number from 1 to {count}. List of properties:",
в русский словарь изменения добавил?

2021-10-10 19:32 UTC, DarkLord5 commented on public/translations/EngText.json
> +    "5": "Remember, Dovahkiin, now you are {1}. It so happened that your homeland is {2}. \nWork is not easy, because you are {3}. As I understand, you are {4}, well, it's your business. \nYour life
А, ты про 81 строку, по идее можно разбить и работать как с отдельными выражениями, но это будет + 15 доп строк кода

2021-10-10 19:34 UTC, DarkLord5 commented on InputOutputProvider.cs
> +            Console.WriteLine(text);
Не надо, это локальное изменение цвета текста, оно само меняется на дефолтное после завершения метода.

2021-10-10 19:36 UTC, DarkLord5 commented on Program.cs
> +            var propertyArr = new int[BaseDict.Count, 2];
Слышишь, я так раньше и сделал, это ты начал выебываться, что лучше длину поставить)

2021-10-10 19:38 UTC, DarkLord5 commented on Program.cs
> +                    InputOutputProvider.PrintText();
Это тупо пропуск строки, так как до этого всё вводится в 1 строку, ладно, этот момент подправлю

2021-10-10 19:39 UTC, DarkLord5 commented on Program.cs
> +            InputOutputProvider.ReadText();
Чтобы консолька не закрылась

2021-10-10 19:42 UTC, DarkLord5 commented on public/translations/EngText.json
> +    "2": "Choose {param} yourself, put the number from 1 to {count}. List of properties:",
Да

2021-10-10 20:53 UTC, seventh-attempt commented on Program.cs
> +            var propertyArr = new int[BaseDict.Count, 2];
ты руками задал размер переменной. опять. И если у тебя изменится размер словаря - тебе нужно будет ещё и перемненную менять. А я хотел чтобы ты после создания словаря создал переменную, содержащую размер словаря, вместо того чтобы подсчитывать её каждый раз, как она тебе нужна. По сути ты делал ненужные операции, и я хотел чтобы ты вместо 5 подсчётов длины словаря сделал 1 подсчёт и использовал его везде, а ты вернул захардкоженую переменную

2021-10-10 20:57 UTC, seventh-attempt commented on public/translations/EngText.json
> +    "5": "Remember, Dovahkiin, now you are {1}. It so happened that your homeland is {2}. \nWork is not easy, because you are {3}. As I understand, you are {4}, well, it's your business. \nYour life
1. не кода, а переводов;
2. у тебя первая версия кода была раза в 2 меньше по размерам, тем не менее мы здесь

2021-10-10 20:59 UTC, DarkLord5 commented on Program.cs
> +            var propertyArr = new int[BaseDict.Count, 2];
Да окей, я тип это сделал. но не заккомитил, ибо щас бы делать коммит ради одной переменной

2021-10-10 21:01 UTC, DarkLord5 commented on Program.cs
> +                InputOutputProvider.PrintText("Choose a language: 1)English(eng). 2)Russian(ru)");
Над этим подумаю, пока пусть так остаётся

2021-10-10 21:02 UTC, DarkLord5 commented on public/translations/EngText.json
> +    "5": "Remember, Dovahkiin, now you are {1}. It so happened that your homeland is {2}. \nWork is not easy, because you are {3}. As I understand, you are {4}, well, it's your business. \nYour life
Ты не понял о чём я, ладно, я в любом случае это уже меняю.

2021-10-10 21:14 UTC, seventh-attempt commented on Program.cs
> +            for (int i = 0; i < paramCount; i++)
очень тяжело читается код. попробуй эту логику немного разбить (хотя бы вынести содержимое этого фора в отдельную функцию и написать докстрингу к нему)

2021-10-12 09:27 UTC, merged